name: Build container release images
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
      flavor: |
        latest = true
    secrets: inherit
